default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.postges[:username] %>
  password: <%= Rails.application.credentials.postges[:password] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: content_wave_development

test:
  <<: *default
  database: content_wave_test

production:
  <<: *default
  database: content_wave_production
  url: <%= ENV['DATABASE_URL'] %>
